apiVersion: v1
kind: Secret
metadata:
  name: revelation-secrets
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  JWT_SECRET: "${JWT_SECRET}"
  TELOXIDE_TOKEN: "${TELOXIDE_TOKEN}"
  YOOKASSA_SHOP_ID: "${YOOKASSA_SHOP_ID}"
  YOOKASSA_SECRET: "${YOOKASSA_SECRET}"
