apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: revelation-ingress
  namespace: revelation
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.revelation.ru
      secretName: revelation-tls
  rules:
    - host: app.revelation.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: revelation-gateway
                port:
                  number: 8080
