apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: revelation

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - server-deployment.yaml
  - gateway-deployment.yaml
  - payments-deployment.yaml
  - bot-deployment.yaml
  - ingress.yaml
